---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.466.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: golang/go@go1.25.6
- name: golangci/golangci-lint@v2.8.0
- name: goreleaser/goreleaser@v2.13.3
- name: securego/gosec@v2.22.11
- name: reviewdog/reviewdog@v0.21.0
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.11.0
- name: rhysd/actionlint@v1.7.10
- name: rust-lang/mdBook@v0.5.2
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.69.0
- name: editorconfig-checker/editorconfig-checker@v3.6.1
