---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.408.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: golang/go@go1.25.1
- name: golangci/golangci-lint@v2.4.0
- name: goreleaser/goreleaser@v2.12.0
- name: securego/gosec@v2.22.8
- name: reviewdog/reviewdog@v0.21.0
- name: mvdan/sh@v3.12.0
- name: koalaman/shellcheck@v0.11.0
- name: rhysd/actionlint@v1.7.7
- name: rust-lang/mdBook@v0.4.52
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.66.0
- name: editorconfig-checker/editorconfig-checker@v3.4.0
