---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.290.0 # renovate: depName=aquaproj/aqua-registry

packages:
- name: dominikh/go-tools/staticcheck@2024.1.1
- name: goreleaser/goreleaser@v1.26.2
- name: securego/gosec@v2.21.4
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.10.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.5
- name: rust-lang/mdBook@v0.4.43
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.58.1
