runs:
  using: composite
  steps:
  - name: Setup Python
    uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
    with:
      python-version-file: .github/dependency/.python-version
      cache: pip
      cache-dependency-path: .github/dependency/requirements.txt
  - name: Setup Pip
    shell: bash
    run: pip install -r .github/dependency/requirements.txt
