runs:
  using: composite
  steps:
  - name: Setup Python
    uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
    with:
      python-version-file: .github/dependency/.python-version
      cache: pip
      cache-dependency-path: .github/dependency/requirements.txt
  - name: Setup Pip
    shell: bash
    run: pip install -r .github/dependency/requirements.txt
