runs:
  using: composite
  steps:
  - name: Setup Python
    uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
    with:
      python-version-file: .github/dependency/.python-version
      cache: pip
      cache-dependency-path: .github/dependency/requirements.txt
  - name: Setup Pip
    shell: bash
    run: pip install -r .github/dependency/requirements.txt
