runs:
  using: composite
  steps:
  - name: Cache Directory
    id: cache-dir
    shell: bash
    run: echo "::set-output name=aqua::${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}"
  - name: Aqua Tools Cache
    uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: ${{ steps.cache-dir.outputs.aqua }}
      key: ${{ runner.os }}-aqua-tools-${{ hashFiles('**/.aqua.yaml') }}-${{ hashFiles('**/actions-cache-version') }}
      restore-keys: |
        ${{ runner.os }}-aqua-tools-${{ hashFiles('**/.aqua.yaml') }}-
        ${{ runner.os }}-aqua-tools-
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
    with:
      aqua_version: v2.54.1
      aqua_opts: -a
