runs:
  using: composite
  steps:
  - name: Cache Directory
    id: cache-dir
    shell: bash
    run: echo "::set-output name=aqua::${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}"
  - name: Aqua Tools Cache
    uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
    with:
      path: ${{ steps.cache-dir.outputs.aqua }}
      key: ${{ runner.os }}-aqua-tools-${{ hashFiles('**/.aqua.yaml') }}-${{ hashFiles('**/actions-cache-version') }}
      restore-keys: |
        ${{ runner.os }}-aqua-tools-${{ hashFiles('**/.aqua.yaml') }}-
        ${{ runner.os }}-aqua-tools-
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@11dd79b4e498d471a9385aa9fb7f62bb5f52a73c # v4.0.4
    with:
      aqua_version: v2.56.0
      aqua_opts: -a
