name: Reviewdog
on:
  push:
    branches:
    - 'main'
permissions:
  contents: read
  checks: write
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup Go
      uses: ./.github/actions/setup-go
    - name: Setup Python
      uses: ./.github/actions/setup-python
    - name: Reviewdog
      run: reviewdog -reporter "github-check" -diff "git diff FETCH_HEAD" -filter-mode "nofilter"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
