name: Reviewdog (shellcheck)
on:
  push:
    branches:
    - 'main'
  pull_request:
    paths:
    - '.github/actions/setup-aqua/action.yaml'
    - '.github/actions/setup-reviewdog/action.yaml'
    - '.github/dependency/actions-cache-version'
    - '.github/workflows/reviewdog-shellcheck.yml'
    - '.aqua.yaml'
    - '.reviewdog.yml'
    - '**.sh'
    - '**.bash'
permissions:
  contents: read
  pull-requests: write
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup Reviewdog
      id: reviewdog
      uses: ./.github/actions/setup-reviewdog
    - name: Reviewdog
      run: reviewdog -runners 'shellcheck' -reporter '${{ steps.reviewdog.outputs.reporter }}' -diff 'git diff FETCH_HEAD'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
