name: Reviewdog (govet)
on:
  workflow_call:
  pull_request:
    paths:
    - '.github/actions/setup-go/action.yaml'
    - '.github/actions/setup-aqua/action.yaml'
    - '.github/actions/setup-reviewdog/action.yaml'
    - '.github/dependency/actions-cache-version'
    - '.github/workflows/reviewdog-govet.yml'
    - '.aqua.yaml'
    - '.reviewdog.yml'
    - 'go.mod'
    - 'go.sum'
    - '**.go'
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - name: Checkout
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - name: Setup Go
      uses: ./.github/actions/setup-go
      with:
        cache: true
        cache-key: vet
    - name: Setup Aqua
      uses: ./.github/actions/setup-aqua
    - name: Setup Reviewdog
      id: reviewdog
      uses: ./.github/actions/setup-reviewdog
    - name: Reviewdog
      run: reviewdog -runners 'govet' -reporter '${{ steps.reviewdog.outputs.reporter }}' -diff 'git diff FETCH_HEAD'
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
